extends: _base_bpcc.yaml

model:
  model_name_or_path: "dllm-hub/ModernBERT-base-chat-v0.1"
  dtype: "bfloat16"
  attn_implementation: null
  lora: false

training:
  output_dir: ".models/modernbert-chat-bpcc-translation-v2"
  num_train_epochs: 12
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 64
  learning_rate: 1.0e-4
  group_by_length: true
  save_steps: 1000
